---
- hosts: localhost
  gather_facts: no
  tasks:

    - name: pull base image
      docker_image:
        name: ubuntu:18.04
        state: present

    - name: build nginx image
      docker_image:
        path: /nginx/Dockerfile
        name: nginx_demo
        state: build

    - name: build redis image
      docker_image:
        path: /redis/Dockerfile
        name: redis_demo
        state: build

    - name: start/restart nginx
      docker_container:
        name: nginx_demo
        image: nginx_demo
        state: started
        restart: yes
        ports:
         - "80:80"
         - "443:443"

    - name: start/restart redis
      docker_container:
        name: redis_demo
        image: redis_demo
        state: started
        restart: yes
        ports:
         - "6379:6379"
